Watching for file changes with StatReloader
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2021 - 03:11:00
Django version 3.2.7, using settings 'carwebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[09/Oct/2021 03:12:03] "GET / HTTP/1.1" 200 54575
[09/Oct/2021 03:12:04] "GET /static/img/logos/mylogo.png HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/Cars/08-10-2021/1893633875.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/Cars/08-10-2021/1896836887.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/Cars/09-10-2021/1894300905.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/Cars/09-10-2021/1894300894.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/Cars/07-10-2021/1902536891.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/Cars/08-10-2021/423366.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/Cars/08-10-2021/2017-lamborghini.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/photo/2021/10/06/photofb.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/photo/2021/10/07/cae.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:04] "GET /media/Cars/08-10-2021/COVER_CENTENARIO.jpg HTTP/1.1" 304 0
[09/Oct/2021 03:12:15] "GET /admin/ HTTP/1.1" 200 7485
[09/Oct/2021 03:12:20] "GET /account/register HTTP/1.1" 200 6615
Not Found: /account/{%
[09/Oct/2021 03:12:21] "GET /account/%7B% HTTP/1.1" 404 3726
[09/Oct/2021 03:12:28] "GET /account/login HTTP/1.1" 200 6612
[09/Oct/2021 03:12:34] "GET /account/logout HTTP/1.1" 302 0
[09/Oct/2021 03:12:34] "GET / HTTP/1.1" 200 54575
[09/Oct/2021 03:13:48] "GET / HTTP/1.1" 200 54585
[09/Oct/2021 03:13:52] "GET /account/login HTTP/1.1" 200 6622
[09/Oct/2021 03:13:55] "GET /account/register HTTP/1.1" 200 6625
[09/Oct/2021 03:19:08] "GET /account/register HTTP/1.1" 200 9622
[09/Oct/2021 03:19:24] "GET /account/login HTTP/1.1" 200 8952
[09/Oct/2021 03:19:31] "GET /account/register HTTP/1.1" 200 9622
[09/Oct/2021 03:20:13] "GET /account/register HTTP/1.1" 200 9903
[09/Oct/2021 03:21:04] "GET /account/login HTTP/1.1" 200 8952
[09/Oct/2021 03:21:34] "GET /account/login HTTP/1.1" 200 8916
[09/Oct/2021 03:21:58] "GET /account/login HTTP/1.1" 200 8954
[09/Oct/2021 03:22:03] "GET / HTTP/1.1" 200 54585
[09/Oct/2021 03:22:16] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828
[09/Oct/2021 03:22:16] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1819
[09/Oct/2021 03:22:16] "GET /static/js/bootstrap-select.js.map HTTP/1.1" 404 1837
[09/Oct/2021 03:22:16] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1834
[09/Oct/2021 03:22:16] "GET /static/css/bootstrap-submenu.css.map HTTP/1.1" 404 1846
[09/Oct/2021 03:23:33] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1834
[09/Oct/2021 03:23:33] "GET /static/css/bootstrap-submenu.css.map HTTP/1.1" 404 1846
[09/Oct/2021 03:23:33] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828
[09/Oct/2021 03:23:33] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1819
[09/Oct/2021 03:23:33] "GET /static/js/bootstrap-select.js.map HTTP/1.1" 404 1837
[09/Oct/2021 03:24:47] "GET /account/register HTTP/1.1" 200 9903
[09/Oct/2021 03:24:52] "GET /account/login HTTP/1.1" 200 8896
[09/Oct/2021 03:25:15] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1819
[09/Oct/2021 03:25:15] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828
[09/Oct/2021 03:25:15] "GET /static/js/bootstrap-select.js.map HTTP/1.1" 404 1837
[09/Oct/2021 03:25:15] "GET /static/css/bootstrap-submenu.css.map HTTP/1.1" 404 1846
[09/Oct/2021 03:25:15] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1834
[09/Oct/2021 03:26:16] "GET /account/login HTTP/1.1" 200 8896
[09/Oct/2021 03:26:16] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1834
[09/Oct/2021 03:26:16] "GET /static/css/bootstrap-submenu.css.map HTTP/1.1" 404 1846
[09/Oct/2021 03:26:17] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1819
[09/Oct/2021 03:26:17] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828
[09/Oct/2021 03:26:17] "GET /static/js/bootstrap-select.js.map HTTP/1.1" 404 1837
[09/Oct/2021 03:26:52] "GET /account/login HTTP/1.1" 200 9021
[09/Oct/2021 03:26:53] "GET /static/css/bootstrap-submenu.css.map HTTP/1.1" 404 1846
[09/Oct/2021 03:26:53] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1834
[09/Oct/2021 03:26:53] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1819
[09/Oct/2021 03:26:53] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828
[09/Oct/2021 03:26:53] "GET /static/js/bootstrap-select.js.map HTTP/1.1" 404 1837
[09/Oct/2021 03:27:40] "GET /account/login HTTP/1.1" 200 9023
[09/Oct/2021 03:28:20] "GET /account/login HTTP/1.1" 200 8954
[09/Oct/2021 03:28:33] "GET /account/login HTTP/1.1" 200 8954
[09/Oct/2021 03:28:48] "GET /account/login HTTP/1.1" 200 8954
[09/Oct/2021 03:29:17] "GET /account/login HTTP/1.1" 200 8979
[09/Oct/2021 03:29:53] "GET /account/login HTTP/1.1" 200 9004
[09/Oct/2021 03:30:04] "GET /account/login HTTP/1.1" 200 9000
[09/Oct/2021 03:31:53] "GET /account/login HTTP/1.1" 200 9415
[09/Oct/2021 03:35:52] "GET /account/login HTTP/1.1" 200 9326
[09/Oct/2021 03:36:45] "GET /account/login HTTP/1.1" 200 9364
[09/Oct/2021 03:37:23] "GET /account/login HTTP/1.1" 200 9317
[09/Oct/2021 03:37:37] "GET /account/login HTTP/1.1" 200 9315
[09/Oct/2021 03:39:48] "GET /account/login HTTP/1.1" 200 9310
[09/Oct/2021 03:40:18] "GET /account/login HTTP/1.1" 200 9300
[09/Oct/2021 03:41:02] "GET /account/login HTTP/1.1" 200 9308
[09/Oct/2021 03:41:50] "GET /account/login HTTP/1.1" 200 9329
[09/Oct/2021 03:43:44] "GET /account/login HTTP/1.1" 200 9308
[09/Oct/2021 03:44:07] "GET /account/login HTTP/1.1" 200 9266
[09/Oct/2021 03:44:42] "GET /account/register HTTP/1.1" 200 9903
[09/Oct/2021 03:45:59] "GET /account/register HTTP/1.1" 200 10534
[09/Oct/2021 03:46:26] "GET /account/register HTTP/1.1" 200 10536
[09/Oct/2021 03:48:04] "GET /account/register HTTP/1.1" 200 10622
[09/Oct/2021 03:50:44] "GET /account/dashboard HTTP/1.1" 200 8077
[09/Oct/2021 03:54:46] "GET /account/register HTTP/1.1" 200 10788
[09/Oct/2021 03:55:00] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828
[09/Oct/2021 03:55:00] "GET /static/js/bootstrap-select.js.map HTTP/1.1" 404 1837
[09/Oct/2021 03:55:00] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1819
[09/Oct/2021 03:55:01] "GET /static/css/bootstrap-submenu.css.map HTTP/1.1" 404 1846
[09/Oct/2021 03:55:01] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1834
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2021 - 03:11:53
Django version 3.2.7, using settings 'carwebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_3' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_3' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_3' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
The 'views_images_3' attribute has no file associated with it.
The 'views_images_4' attribute has no file associated with it.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "E:\Programing\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Programing\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\carwebsite\urls.py", line 25, in <module>
    path('account/', include('account.urls')),
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\account\urls.py", line 2, in <module>
    from . import views
  File "E:\Programing\projects\carwebsite_django\account\views.py", line 6
    if request.def FunctionName(self, args):
               ^
SyntaxError: invalid syntax
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "E:\Programing\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Programing\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\carwebsite\urls.py", line 25, in <module>
    path('account/', include('account.urls')),
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\account\urls.py", line 2, in <module>
    from . import views
  File "E:\Programing\projects\carwebsite_django\account\views.py", line 6
    if request.meth
                  ^
SyntaxError: invalid syntax
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "E:\Programing\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Programing\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\carwebsite\urls.py", line 25, in <module>
    path('account/', include('account.urls')),
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\account\urls.py", line 2, in <module>
    from . import views
  File "E:\Programing\projects\carwebsite_django\account\views.py", line 6
    if request.def (self, args):
               ^
SyntaxError: invalid syntax
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "E:\Programing\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Programing\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\carwebsite\urls.py", line 25, in <module>
    path('account/', include('account.urls')),
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\account\urls.py", line 2, in <module>
    from . import views
  File "E:\Programing\projects\carwebsite_django\account\views.py", line 6
    if request.method 
                     ^
SyntaxError: invalid syntax
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "E:\Programing\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Programing\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\carwebsite\urls.py", line 25, in <module>
    path('account/', include('account.urls')),
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "E:\Programing\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Programing\projects\carwebsite_django\account\urls.py", line 2, in <module>
    from . import views
  File "E:\Programing\projects\carwebsite_django\account\views.py", line 6
    if request.method == 'POST'
                              ^
SyntaxError: invalid syntax
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2021 - 04:02:32
Django version 3.2.7, using settings 'carwebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2021 - 04:02:44
Django version 3.2.7, using settings 'carwebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
E:\Programing\projects\carwebsite_django\account\views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2021 - 04:02:49
Django version 3.2.7, using settings 'carwebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Watching for file changes with StatReloader
[09/Oct/2021 04:03:00] "GET /account/register HTTP/1.1" 200 10842
[09/Oct/2021 04:03:01] "GET /static/css/bootstrap-submenu.css.map HTTP/1.1" 404 1846
[09/Oct/2021 04:03:01] "GET /static/css/bootstrap.min.css.map HTTP/1.1" 404 1834
[09/Oct/2021 04:03:02] "GET /static/js/popper.min.js.map HTTP/1.1" 404 1819
[09/Oct/2021 04:03:02] "GET /static/js/bootstrap-select.js.map HTTP/1.1" 404 1837
[09/Oct/2021 04:03:02] "GET /static/js/bootstrap.min.js.map HTTP/1.1" 404 1828
[09/Oct/2021 04:03:52] "POST /account/register HTTP/1.1" 302 0
[09/Oct/2021 04:03:52] "GET /account/login HTTP/1.1" 200 9426
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2021 - 04:02:54
Django version 3.2.7, using settings 'carwebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
this was a post request
Traceback (most recent call last):
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\commands\runserver.py", line 96, in handle
    self.run(**options)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\commands\runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\utils\autoreload.py", line 641, in run_with_reloader
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\core\management\base.py", line 367, in run_from_argv
    connections.close_all()
  File "E:\Programing\projects\carwebsite_django\cardj\lib\site-packages\django\db\utils.py", line 209, in close_all
    try:
KeyboardInterrupt
^C